[package]
name = "similarity"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = { version = "1.0" }
tree-sitter = { version = "0.24" }
tree-sitter-c = { version = "0.23" }
strsim = { version = "0.11.1" }
